-- Auto-generated by scripts/gen-seed.ts. Do not edit by hand.
-- Seeds initial published content for the public hub pages.
truncate table public.content_items;

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'blog', 'how-to-read-newspaper-for-clat', 'How to read the newspaper for CLAT 2027', 'A daily 35-minute routine for legal awareness, vocabulary, and current affairs retention.', 'Study Plans',
  ARRAY['12 min read', 'Beginner', 'Updated today']::text[], ARRAY['Best for Class 11–12 students', 'Works for CLAT and AILET', 'Needs one notebook and one newspaper']::text[], ARRAY['Read editorials with a legal lens.', 'Make issue-based notes, not date-based notes.', 'Revise every Sunday with mock passages.']::text[],
  '[{"heading":"Definition","body":"CLAT newspaper reading means extracting legal, political, economic, and social issues that can become passage-based questions."},{"heading":"Daily timeline","body":"Spend 10 minutes scanning headlines, 15 minutes reading one editorial, and 10 minutes writing five exam-ready bullet points."},{"heading":"Common mistake","body":"Students copy facts without context. Instead, write why the issue matters and which constitutional value it connects to."}]'::jsonb, '[{"q":"Who should read this?","a":"CLAT and AILET aspirants who want a clear, structured answer before choosing their next step."},{"q":"Is this useful for beginners?","a":"Yes. Each guide starts with basics, key facts, and a practical action checklist."}]'::jsonb, 'published', 0
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'blog', 'clat-legal-reasoning-strategy', 'CLAT legal reasoning strategy for first-time aspirants', 'Understand principles, facts, exceptions, and elimination without memorising law books.', 'Legal GK',
  ARRAY['10 min read', 'Beginner', 'Popular']::text[], ARRAY['No prior law knowledge needed', 'Practice principle-fact mapping', 'Review mistakes by rule type']::text[], ARRAY['Start with the rule, not the options.', 'Mark exceptions in the passage.', 'Eliminate choices that add outside assumptions.']::text[],
  '[{"heading":"Definition","body":"Legal reasoning tests whether you can apply a given rule to a new situation, not whether you know case law."},{"heading":"Method","body":"Underline the principle, identify the fact trigger, compare all options, and choose the least assumption-heavy answer."},{"heading":"Practice plan","body":"Solve 20 questions daily and maintain a mistake log with rule, trigger, trap, and corrected reasoning."}]'::jsonb, '[{"q":"Who should read this?","a":"CLAT and AILET aspirants who want a clear, structured answer before choosing their next step."},{"q":"Is this useful for beginners?","a":"Yes. Each guide starts with basics, key facts, and a practical action checklist."}]'::jsonb, 'published', 1
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'blog', 'monthly-current-affairs-revision', 'Monthly current affairs revision table for CLAT', 'A structured way to turn news into quick revision blocks and mock-ready memory.', 'Current Affairs',
  ARRAY['8 min read', 'Revision', 'Recently updated']::text[], ARRAY['Use weekly buckets', 'Revise with themes', 'Connect events to static GK']::text[], ARRAY['Group news by themes.', 'Use one-page monthly sheets.', 'Attach one sample question per issue.']::text[],
  '[{"heading":"Key facts","body":"CLAT current affairs rewards depth, so one issue should include background, institution, controversy, and outcome."},{"heading":"Table format","body":"Use columns for topic, why in news, static link, legal link, and likely question angle."},{"heading":"Revision","body":"Revise monthly sheets on day 7, day 21, and before every full-length mock."}]'::jsonb, '[{"q":"Who should read this?","a":"CLAT and AILET aspirants who want a clear, structured answer before choosing their next step."},{"q":"Is this useful for beginners?","a":"Yes. Each guide starts with basics, key facts, and a practical action checklist."}]'::jsonb, 'published', 2
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'faculties', 'ishaan-mehra', 'Adv. Ishaan Mehra', 'Legal Reasoning mentor · NLSIU Bangalore · Constitution and principle-fact application.', 'Legal Reasoning',
  ARRAY['8 years', '4.9 rating', '2,000+ mentored']::text[], ARRAY['Education: NLSIU Bangalore', 'Specialization: Legal reasoning', 'Available: Lucknow + Online']::text[], ARRAY['Teaches through examples.', 'Focuses on reading the rule carefully.', 'Runs weekly legal doubt clinics.']::text[],
  '[{"heading":"Teaching philosophy","body":"Law entrance preparation should train students to think clearly, not memorise random legal facts."},{"heading":"Achievements","body":"Mentored multiple top-rank students through legal reasoning, mock analysis, and interview preparation."},{"heading":"Courses taught","body":"CLAT two-year, AILET intensive, and foundation legal reasoning modules."}]'::jsonb, '[{"q":"Does he teach beginners?","a":"Yes. His classes start with rule reading and simple everyday examples."},{"q":"Are demo lectures available?","a":"Demo lectures can be requested during counselling."}]'::jsonb, 'published', 0
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'faculties', 'riya-kapoor', 'Prof. Riya Kapoor', 'English and comprehension mentor · NALSAR Hyderabad · Editorial reading systems.', 'English',
  ARRAY['7 years', 'Reading expert', '1,500+ students']::text[], ARRAY['Education: NALSAR Hyderabad', 'Specialization: English', 'Available: Online + Delhi']::text[], ARRAY['Builds vocabulary in context.', 'Improves passage stamina.', 'Uses daily reading logs.']::text[],
  '[{"heading":"About","body":"Riya helps students move from slow, anxious reading to structured comprehension with evidence-based answer selection."},{"heading":"Teaching method","body":"Classes include editorial breakdowns, tone recognition, vocabulary mapping, and timed passage review."},{"heading":"Results produced","body":"Students improve reading speed and accuracy through measured weekly targets."}]'::jsonb, '[{"q":"Can weak English students join?","a":"Yes. The method is designed for gradual improvement."},{"q":"Does she teach vocabulary?","a":"Yes, through context and revision sheets, not rote word lists."}]'::jsonb, 'published', 1
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'branches', 'lucknow-hazratganj', 'TCR Lucknow · Hazratganj', 'Central Lucknow branch near Hazratganj Metro with library, counselling room, and hybrid classrooms.', 'Lucknow',
  ARRAY['4.9 rating', 'Open 8 AM–8 PM', 'Metro nearby']::text[], ARRAY['Phone: +91 92207 61399', 'Facilities: Library, AC classrooms', 'Courses: CLAT, AILET, Foundation']::text[], ARRAY['Easy metro access.', 'Parent counselling available.', 'Weekly mock analysis rooms.']::text[],
  '[{"heading":"Address","body":"Hazratganj, Lucknow. Full landmark and map embed can be connected in the next phase."},{"heading":"Facilities","body":"Classrooms, reading room, counselling desk, doubt area, and test review support."},{"heading":"Batch timings","body":"Morning, evening, and weekend batches can be displayed dynamically once the admin panel is added."}]'::jsonb, '[{"q":"Is parking available?","a":"Limited nearby parking is available depending on the batch time."},{"q":"Can parents visit?","a":"Yes. Counselling slots can be booked before visiting."}]'::jsonb, 'published', 0
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'branches', 'delhi-karol-bagh', 'TCR Delhi · Karol Bagh', 'Central Delhi classroom hub for CLAT and AILET students with weekend and evening batches.', 'Delhi',
  ARRAY['4.8 rating', 'Weekend batches', 'Directions ready']::text[], ARRAY['Phone: +91 92207 61399', 'Facilities: AC classrooms', 'Courses: CLAT, AILET']::text[], ARRAY['Designed for school students.', 'Close to central transport.', 'Hybrid support available.']::text[],
  '[{"heading":"Nearby landmarks","body":"Karol Bagh metro and central coaching district landmarks can be added with geo coordinates."},{"heading":"Courses","body":"CLAT two-year, AILET intensive, and crash revision batches."},{"heading":"Reviews","body":"Student and parent reviews can be connected to this profile for local trust signals."}]'::jsonb, '[{"q":"Are weekend batches available?","a":"Yes, weekend options are part of the sample branch structure."},{"q":"Is a demo class possible?","a":"A demo can be requested from the enquiry form."}]'::jsonb, 'published', 1
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'toppers', 'aaryan-singh-air-1-ailet-2026', 'Aaryan Singh · AIR 1 AILET 2026', 'First-year TCR result with a structured mock review habit and daily legal reading routine.', 'AILET 2026',
  ARRAY['AIR 1', 'AILET', 'Lucknow']::text[], ARRAY['Course: AILET Intensive', 'Preparation time: 11 months', 'Branch: Lucknow']::text[], ARRAY['Focused on mock correction.', 'Read editorials daily.', 'Used mentor feedback every week.']::text[],
  '[{"heading":"Daily routine","body":"Two reading blocks, one timed reasoning set, current affairs revision, and mock correction notes."},{"heading":"Mistakes","body":"Early mistakes included rushing legal passages and ignoring option wording."},{"heading":"Teacher advice","body":"Review every wrong answer until the trap becomes obvious."}]'::jsonb, '[{"q":"Which course did he take?","a":"The sample profile maps him to the AILET Intensive Program."},{"q":"Can students follow his routine?","a":"Yes, but it should be adjusted by class, school hours, and current mock score."}]'::jsonb, 'published', 0
);

insert into public.content_items (kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (
  'toppers', 'meera-iyer-air-7-clat-2026', 'Meera Iyer · AIR 7 CLAT 2026', 'A CLAT success story built on reading speed, sectional strategy, and calm revision.', 'CLAT 2026',
  ARRAY['AIR 7', 'CLAT', 'Hybrid']::text[], ARRAY['Course: CLAT Two-Year', 'Score: 112+ sample', 'Mode: Hybrid']::text[], ARRAY['Improved passage stamina.', 'Kept a GK issue tracker.', 'Reduced silly mistakes.']::text[],
  '[{"heading":"Books used","body":"Editorial notes, TCR legal reasoning sheets, current affairs compilations, and full-length mock papers."},{"heading":"Study plan","body":"Concept work in year one, mock volume and analysis in year two."},{"heading":"Recommended course","body":"Students starting early should compare the CLAT Two-Year Program."}]'::jsonb, '[{"q":"Was she an early starter?","a":"Yes, this sample profile represents a two-year prep path."},{"q":"What was the biggest improvement area?","a":"Reading speed and current affairs retention."}]'::jsonb, 'published', 1
);
