import { useState } from "react";
import {
  AlertTriangle, ArrowRight, CheckCircle2, ChevronDown, Clock, Copy, Edit3,
  Eye, FileText, Filter, Image, Loader2, MoreHorizontal, Plus, Search, Trash2,
} from "lucide-react";
import { activityFeed, adminEntities, blogRows, dashboardMetrics, entityRows, type AdminEntity } from "@/lib/admin/admin-data";

export function AdminDashboardScreen() {
  return (
    <div className="space-y-6" data-testid="admin-dashboard-screen">
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" data-testid="admin-analytics-grid">
        {dashboardMetrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}
      </section>
      <section className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
        <div className="rounded-3xl border border-border bg-card p-5 shadow-sm" data-testid="admin-chart-card">
          <div className="flex items-center justify-between gap-4"><div><h2 className="font-serif text-2xl font-black">Admissions velocity</h2><p className="mt-1 text-sm text-muted-foreground">Lead to admission trend across courses and branches.</p></div><StatusBadge status="Live" /></div>
          <div className="mt-8 flex h-72 items-end gap-3 rounded-2xl bg-secondary p-4" data-testid="admin-chart-placeholder">
            {[42, 58, 36, 72, 64, 82, 78, 92, 70, 88, 96, 84].map((height, index) => <div key={index} className="flex-1 rounded-t-xl bg-primary/80 transition-transform duration-200 hover:scale-y-105" style={{ height: `${height}%` }} />)}
          </div>
        </div>
        <div className="grid gap-6">
          <Panel title="Quick actions" testId="admin-quick-actions-panel">
            {[["Create Blog", "Draft a new SEO article"], ["Add Batch", "Open admission intake"], ["Upload Media", "Images and files"], ["Invite User", "Role-based access"]].map(([title, sub]) => <button key={title} type="button" data-testid={`quick-action-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`} className="flex min-h-16 w-full items-center justify-between rounded-2xl border border-border bg-background px-4 text-left transition-transform duration-200 hover:-translate-y-0.5"><span><span className="block font-bold">{title}</span><span className="text-sm text-muted-foreground">{sub}</span></span><ArrowRight className="h-4 w-4 text-primary" /></button>)}
          </Panel>
          <Panel title="Recent activity" testId="admin-activity-panel">
            {activityFeed.map((activity) => <div key={activity} className="flex gap-3 rounded-xl bg-secondary p-3" data-testid={`activity-${activity.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}><Clock className="mt-0.5 h-4 w-4 text-primary" /><p className="text-sm font-medium">{activity}</p></div>)}
          </Panel>
        </div>
      </section>
      <section className="grid gap-6 xl:grid-cols-3">
        <MiniList title="Upcoming batches" items={["AILET Intensive · 8 seats left", "CLAT Weekend · starts Aug 5", "Foundation · parent orientation"]} />
        <MiniList title="Latest blogs" items={blogRows.slice(0, 3).map((row) => row.title)} />
        <MiniList title="Recent admissions" items={["Ananya · CLAT Two-Year", "Rohan · AILET Intensive", "Meera · Foundation"]} />
      </section>
    </div>
  );
}

export function ModuleOverviewScreen({ section }: { section: string }) {
  const entities = adminEntities.filter((entity) => entity.section === section || (section === "CMS" && ["blogs", "resources"].includes(entity.key)) || (section === "Academics" && ["courses", "batches", "faculties"].includes(entity.key)));
  return (
    <div className="space-y-6" data-testid={`admin-${section.toLowerCase()}-overview-screen`}>
      <StateShowcase />
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
        {(entities.length ? entities : adminEntities.slice(0, 6)).map((entity) => <EntityCard key={entity.key} entity={entity} />)}
      </div>
    </div>
  );
}

export function CrudScreen({ entity }: { entity: AdminEntity }) {
  const [drawer, setDrawer] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const rows = entity.key === "blogs" ? blogRows.map((row) => ({ name: row.title, type: row.category, owner: row.author, status: row.status, updated: row.updated, score: row.score })) : entityRows;
  return (
    <div className="space-y-6" data-testid={`admin-${entity.key}-crud-screen`}>
      <section className="rounded-3xl border border-border bg-card p-5 shadow-sm">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div><h2 className="font-serif text-3xl font-black">{entity.label}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{entity.description}</p></div>
          <button type="button" data-testid={`${entity.key}-create-button`} onClick={() => setDrawer(true)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground"><Plus className="h-4 w-4" /> New {entity.label.slice(0, -1) || entity.label}</button>
        </div>
        <div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto_auto_auto]">
          <label className="flex min-h-12 items-center gap-3 rounded-xl border border-border bg-background px-4"><Search className="h-4 w-4 text-primary" /><input data-testid={`${entity.key}-search-input`} placeholder={`Search ${entity.label.toLowerCase()}...`} className="w-full bg-transparent text-sm font-bold outline-none" /></label>
          {['Status', 'Owner', 'Updated'].map((filter) => <button key={filter} type="button" data-testid={`${entity.key}-filter-${filter.toLowerCase()}-button`} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-border bg-background px-4 text-sm font-bold"><Filter className="h-4 w-4" />{filter}<ChevronDown className="h-4 w-4" /></button>)}
        </div>
        <div className="mt-4 flex flex-wrap gap-2" data-testid={`${entity.key}-bulk-actions`}>
          {['Publish', 'Archive', 'Duplicate'].map((action) => <button key={action} type="button" data-testid={`${entity.key}-bulk-${action.toLowerCase()}-button`} className="min-h-10 rounded-lg border border-border bg-background px-3 text-xs font-bold">{action}</button>)}
          <button type="button" onClick={() => setConfirmOpen(true)} data-testid={`${entity.key}-bulk-delete-button`} className="min-h-10 rounded-lg border border-border bg-background px-3 text-xs font-bold text-primary">Delete</button>
        </div>
      </section>
      <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm" data-testid={`${entity.key}-data-table`}>
        <div className="hidden overflow-x-auto lg:block">
          <table className="w-full text-left text-sm"><thead className="border-b border-border bg-secondary text-xs uppercase tracking-[0.14em] text-muted-foreground"><tr>{['Name', 'Type', 'Owner', 'Status', 'Updated', 'SEO', 'Actions'].map((h) => <th key={h} className="px-5 py-4 font-bold"><button type="button" data-testid={`${entity.key}-sort-${h.toLowerCase()}-button`} className="inline-flex items-center gap-1 font-bold">{h}{h !== 'Actions' && <ChevronDown className="h-3 w-3" />}</button></th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.name} className="border-b border-border last:border-0"><td className="px-5 py-4 font-bold">{row.name}</td><td className="px-5 py-4 text-muted-foreground">{row.type}</td><td className="px-5 py-4">{row.owner}</td><td className="px-5 py-4"><StatusBadge status={row.status} /></td><td className="px-5 py-4 text-muted-foreground">{row.updated}</td><td className="px-5 py-4"><span className="font-bold text-primary">{('score' in row && row.score) || '92'}</span></td><td className="px-5 py-4"><RowActions onEdit={() => setDrawer(true)} onDelete={() => setConfirmOpen(true)} /></td></tr>)}</tbody></table>
        </div>
        <div className="grid gap-3 p-3 lg:hidden" data-testid={`${entity.key}-mobile-cards`}>{rows.map((row) => <article key={row.name} className="rounded-2xl border border-border bg-background p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-serif text-xl font-black">{row.name}</h3><p className="mt-1 text-sm text-muted-foreground">{row.type} · {row.owner}</p></div><StatusBadge status={row.status} /></div><div className="mt-4 flex items-center justify-between text-sm"><span className="text-muted-foreground">{row.updated}</span><RowActions onEdit={() => setDrawer(true)} /></div></article>)}</div>
        <div className="flex flex-col gap-3 border-t border-border px-5 py-4 sm:flex-row sm:items-center sm:justify-between" data-testid={`${entity.key}-pagination`}><p className="text-sm text-muted-foreground">Showing 1–4 of {entity.count}</p><div className="flex gap-2"><button className="min-h-10 rounded-lg border border-border px-3 text-sm font-bold" data-testid={`${entity.key}-previous-page-button`}>Previous</button><button className="min-h-10 rounded-lg border border-border px-3 text-sm font-bold" data-testid={`${entity.key}-next-page-button`}>Next</button></div></div>
      </section>
      <CrudStateTemplates entityKey={entity.key} />
      {drawer && (entity.key === "blogs" ? <BlogEditorDrawer onClose={() => setDrawer(false)} /> : <GenericEditorDrawer entity={entity} onClose={() => setDrawer(false)} />)}
      {confirmOpen && <ConfirmDialog entity={entity.label} onClose={() => setConfirmOpen(false)} />}
    </div>
  );
}

export function AdminLoginScreen() {
  return (
    <div className="min-h-screen bg-[linear-gradient(135deg,#fafafa,#f3f0e8,#fff)] px-4 py-10 text-foreground" data-testid="admin-login-screen">
      <div className="mx-auto grid min-h-[calc(100vh-5rem)] max-w-[1100px] items-center gap-8 lg:grid-cols-[0.95fr_1.05fr]">
        <section className="hidden rounded-[2rem] border border-border bg-card p-8 shadow-sm lg:block" data-testid="admin-login-brand-panel"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">The Court Room OS</p><h1 className="mt-5 font-serif text-5xl font-black leading-tight">Premium coaching operations, without ERP clutter.</h1><p className="mt-5 text-muted-foreground">Manage content, batches, SEO, results, users and admissions from one calm workspace.</p><div className="mt-8 grid gap-3">{['Role-aware access', 'CMS + Academics + SEO', 'Mobile-first admin'].map((item) => <div key={item} className="rounded-xl bg-secondary p-4 font-bold"><CheckCircle2 className="mr-2 inline h-5 w-5 text-primary" />{item}</div>)}</div></section>
        <section className="mx-auto w-full max-w-md rounded-[2rem] border border-border bg-card p-6 shadow-sm sm:p-8" data-testid="admin-login-card"><p className="font-serif text-4xl font-black text-primary">TCR Admin</p><h2 className="mt-6 font-serif text-3xl font-black">Sign in to workspace</h2><p className="mt-2 text-sm text-muted-foreground">Choose a role preview and continue with your admin account.</p><div className="mt-5 grid grid-cols-3 gap-2">{['Owner', 'Editor', 'Counsellor'].map((role) => <button key={role} data-testid={`admin-login-role-${role.toLowerCase()}-button`} className="min-h-11 rounded-xl border border-border bg-secondary text-xs font-bold">{role}</button>)}</div><label className="mt-6 block text-sm font-bold">Email<input data-testid="admin-login-email-input" className="mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-4 outline-none focus:ring-2 focus:ring-ring" placeholder="admin@thecourtroom.in" /></label><label className="mt-4 block text-sm font-bold">Password<input data-testid="admin-login-password-input" type="password" className="mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-4 outline-none focus:ring-2 focus:ring-ring" placeholder="••••••••" /></label><button data-testid="admin-login-submit-button" className="mt-6 min-h-12 w-full rounded-xl bg-primary text-sm font-bold text-primary-foreground">Continue</button><a href="/admin/forgot-password" data-testid="admin-forgot-password-link" className="mt-4 block text-center text-sm font-bold text-primary">Forgot password?</a></section>
      </div>
    </div>
  );
}

export function ForgotPasswordScreen() {
  return <div className="flex min-h-screen items-center justify-center bg-background px-4" data-testid="admin-forgot-password-screen"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-8 shadow-sm"><h1 className="font-serif text-3xl font-black">Reset password</h1><p className="mt-2 text-sm text-muted-foreground">Enter your email and we will send reset instructions.</p><input data-testid="admin-reset-email-input" className="mt-6 min-h-12 w-full rounded-xl border border-border bg-background px-4" placeholder="admin@thecourtroom.in" /><button data-testid="admin-reset-submit-button" className="mt-4 min-h-12 w-full rounded-xl bg-primary text-sm font-bold text-primary-foreground">Send reset link</button><a href="/admin/login" data-testid="admin-back-login-link" className="mt-4 block text-center text-sm font-bold text-primary">Back to login</a></div></div>;
}

function BlogEditorDrawer({ onClose }: { onClose: () => void }) {
  return <EditorShell title="Blog editor" onClose={onClose} testId="blog-editor-drawer"><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-5"><Tabs labels={["Content", "SEO", "Media", "Relations"]} /><Field label="Title" value="How to read the newspaper for CLAT 2027" testId="blog-title" /><Field label="Slug" value="how-to-read-newspaper-for-clat" testId="blog-slug" /><div className="grid gap-4 md:grid-cols-2"><Field label="Category" value="Study Plans" testId="blog-category" /><Field label="Reading time" value="12 min" testId="blog-reading-time" /></div><div className="grid gap-4 md:grid-cols-2"><Field label="Author" value="Riya Kapoor" testId="blog-author" /><Field label="Editor" value="Editorial Desk" testId="blog-editor" /></div><RichText /><TagInput tags={["CLAT", "Reading", "Current Affairs"]} /><SeoPreview /></div><aside className="space-y-5"><MediaPicker /><LivePreview /><ValidationCard /></aside></div></EditorShell>;
}

function GenericEditorDrawer({ entity, onClose }: { entity: AdminEntity; onClose: () => void }) {
  return <EditorShell title={`${entity.label} editor`} onClose={onClose} testId={`${entity.key}-editor-drawer`}><div className="space-y-5"><Tabs labels={["Overview", "Details", "SEO", "Media"]} />{entity.fields.slice(0, 8).map((field) => <Field key={field} label={field} value={`Sample ${field.toLowerCase()}`} testId={`${entity.key}-${field.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`} />)}<SeoPreview /></div></EditorShell>;
}

function EditorShell({ title, onClose, children, testId }: { title: string; onClose: () => void; children: React.ReactNode; testId: string }) {
  return <div className="fixed inset-0 z-[70] bg-foreground/30" data-testid={testId}><aside className="ml-auto flex h-full w-full max-w-5xl flex-col overflow-hidden bg-background shadow-2xl"><header className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-serif text-2xl font-black">{title}</h2><p className="text-xs font-bold text-muted-foreground"><Loader2 className="mr-1 inline h-3 w-3 animate-spin" /> Auto-saving draft</p></div><button onClick={onClose} data-testid={`${testId}-close-button`} className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold">Close</button></header><div className="flex-1 overflow-y-auto p-5">{children}</div><footer className="sticky bottom-0 flex flex-col gap-3 border-t border-border bg-card px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">All changes are UI-only in this phase.</p><div className="flex gap-2"><button data-testid={`${testId}-discard-button`} className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold">Discard</button><button data-testid={`${testId}-save-button`} className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Save changes</button></div></footer></aside></div>;
}

function MetricCard({ label, value, change }: { label: string; value: string; change: string; tone: string }) { return <article className="rounded-3xl border border-border bg-card p-5 shadow-sm" data-testid={`metric-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}><p className="text-sm font-bold text-muted-foreground">{label}</p><p className="mt-3 font-serif text-4xl font-black">{value}</p><p className="mt-3 text-sm font-bold text-primary">{change}</p></article>; }
function Panel({ title, children, testId }: { title: string; children: React.ReactNode; testId: string }) { return <section className="rounded-3xl border border-border bg-card p-5 shadow-sm" data-testid={testId}><h2 className="font-serif text-2xl font-black">{title}</h2><div className="mt-4 space-y-3">{children}</div></section>; }
function MiniList({ title, items }: { title: string; items: string[] }) { return <Panel title={title} testId={`mini-list-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`}>{items.map((item) => <div key={item} className="flex items-center justify-between rounded-xl bg-secondary p-4 text-sm font-bold"><span>{item}</span><ArrowRight className="h-4 w-4 text-primary" /></div>)}</Panel>; }
function EntityCard({ entity }: { entity: AdminEntity }) { return <article className="rounded-3xl border border-border bg-card p-5 shadow-sm transition-transform duration-200 hover:-translate-y-1" data-testid={`entity-card-${entity.key}`}><entity.icon className="h-8 w-8 text-primary" /><div className="mt-5 flex items-start justify-between gap-3"><div><h2 className="font-serif text-2xl font-black">{entity.label}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{entity.description}</p></div><StatusBadge status={entity.status} /></div><p className="mt-5 text-sm font-bold text-primary">{entity.count} records</p><a href={entity.path} data-testid={`entity-card-${entity.key}-link`} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-secondary px-4 text-sm font-bold">Open module <ArrowRight className="h-4 w-4" /></a></article>; }
function StateShowcase() { return <div className="grid gap-4 md:grid-cols-3" data-testid="admin-state-showcase"><div className="rounded-2xl border border-border bg-card p-5"><Loader2 className="h-5 w-5 animate-spin text-primary" /><p className="mt-3 font-bold">Skeleton loaders ready</p><div className="mt-3 space-y-2"><div className="h-3 rounded bg-secondary" /><div className="h-3 w-2/3 rounded bg-secondary" /></div></div><div className="rounded-2xl border border-border bg-card p-5"><AlertTriangle className="h-5 w-5 text-primary" /><p className="mt-3 font-bold">Error state</p><p className="text-sm text-muted-foreground">Retry and support copy patterns.</p></div><div className="rounded-2xl border border-border bg-card p-5"><CheckCircle2 className="h-5 w-5 text-primary" /><p className="mt-3 font-bold">Success state</p><p className="text-sm text-muted-foreground">Saved, published and synced feedback.</p></div></div>; }
function StatusBadge({ status }: { status: string }) { return <span data-testid={`status-badge-${status.toLowerCase()}`} className="inline-flex min-h-8 items-center rounded-full bg-secondary px-3 text-xs font-bold text-foreground">{status}</span>; }
function RowActions({ onEdit, onDelete }: { onEdit: () => void; onDelete?: () => void }) { return <div className="flex gap-1"><button onClick={onEdit} data-testid="row-edit-button" className="min-h-9 min-w-9 rounded-lg border border-border"><Edit3 className="mx-auto h-4 w-4" /></button><button data-testid="row-preview-button" className="min-h-9 min-w-9 rounded-lg border border-border"><Eye className="mx-auto h-4 w-4" /></button><button onClick={onDelete} data-testid="row-delete-button" className="min-h-9 min-w-9 rounded-lg border border-border"><Trash2 className="mx-auto h-4 w-4" /></button><button data-testid="row-more-button" className="min-h-9 min-w-9 rounded-lg border border-border"><MoreHorizontal className="mx-auto h-4 w-4" /></button></div>; }
function CrudStateTemplates({ entityKey }: { entityKey: string }) { return <section className="grid gap-4 md:grid-cols-3" data-testid={`${entityKey}-crud-state-templates`}><div className="rounded-2xl border border-dashed border-border bg-card p-5" data-testid={`${entityKey}-empty-state`}><FileText className="h-6 w-6 text-primary" /><p className="mt-3 font-bold">No records yet</p><p className="mt-1 text-sm text-muted-foreground">Empty state pattern for filtered or new modules.</p></div><div className="rounded-2xl border border-border bg-card p-5" data-testid={`${entityKey}-skeleton-state`}><Loader2 className="h-5 w-5 animate-spin text-primary" /><div className="mt-4 space-y-2"><div className="h-3 rounded bg-secondary" /><div className="h-3 w-2/3 rounded bg-secondary" /><div className="h-3 w-1/2 rounded bg-secondary" /></div></div><div className="rounded-2xl border border-border bg-card p-5" data-testid={`${entityKey}-success-state`}><CheckCircle2 className="h-6 w-6 text-primary" /><p className="mt-3 font-bold">Saved successfully</p><p className="mt-1 text-sm text-muted-foreground">Success feedback for create/edit actions.</p></div></section>; }
function ConfirmDialog({ entity, onClose }: { entity: string; onClose: () => void }) { return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-foreground/35 px-4" data-testid="admin-confirm-dialog"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-6 shadow-2xl"><AlertTriangle className="h-8 w-8 text-primary" /><h2 className="mt-4 font-serif text-2xl font-black">Delete selected {entity}?</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">This confirmation dialog is UI-only now and can later connect to backend delete APIs.</p><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} data-testid="admin-confirm-cancel-button" className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold">Cancel</button><button onClick={onClose} data-testid="admin-confirm-delete-button" className="min-h-11 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Delete</button></div></div></div>; }
function Tabs({ labels }: { labels: string[] }) { return <div className="flex gap-2 overflow-x-auto rounded-2xl bg-secondary p-1" data-testid="editor-tabs">{labels.map((label, i) => <button key={label} data-testid={`editor-tab-${label.toLowerCase()}`} className={`min-h-11 rounded-xl px-4 text-sm font-bold ${i === 0 ? "bg-card shadow-sm" : ""}`}>{label}</button>)}</div>; }
function Field({ label, value, testId }: { label: string; value: string; testId: string }) { return <label className="block text-sm font-bold">{label}<input data-testid={`${testId}-input`} defaultValue={value} className="mt-2 min-h-12 w-full rounded-xl border border-border bg-card px-4 outline-none focus:ring-2 focus:ring-ring" /></label>; }
function RichText() { return <div data-testid="blog-rich-text-editor" className="rounded-2xl border border-border bg-card p-4"><p className="text-sm font-bold">Rich text editor</p><div className="mt-3 min-h-44 rounded-xl bg-secondary p-4 text-sm text-muted-foreground">Write article content with headings, examples, FAQs, tables and summaries...</div></div>; }
function TagInput({ tags }: { tags: string[] }) { return <div data-testid="blog-tag-input" className="rounded-2xl border border-border bg-card p-4"><p className="text-sm font-bold">Tags</p><div className="mt-3 flex flex-wrap gap-2">{tags.map((tag) => <span key={tag} className="rounded-full bg-secondary px-3 py-1 text-xs font-bold">{tag}</span>)}<button className="rounded-full border border-border px-3 py-1 text-xs font-bold">+ Add tag</button></div></div>; }
function SeoPreview() { return <section data-testid="seo-preview-card" className="rounded-2xl border border-border bg-card p-4"><p className="text-sm font-bold">SEO + Open Graph preview</p><div className="mt-3 rounded-xl border border-border bg-background p-4"><p className="text-xs text-primary">thecourtroom.in/blog/how-to-read-newspaper-for-clat</p><p className="mt-1 font-serif text-xl font-black">How to read the newspaper for CLAT 2027</p><p className="mt-1 text-sm text-muted-foreground">A daily routine for legal awareness, vocabulary and current affairs retention.</p></div><pre className="mt-3 overflow-x-auto rounded-xl bg-secondary p-3 text-xs">{`{ "@type": "Article", "headline": "CLAT guide" }`}</pre></section>; }
function MediaPicker() { return <section data-testid="media-picker-card" className="rounded-2xl border border-border bg-card p-4"><Image className="h-6 w-6 text-primary" /><p className="mt-3 font-bold">Media picker</p><div className="mt-3 flex aspect-video items-center justify-center rounded-xl border border-dashed border-border bg-secondary text-sm text-muted-foreground">Drop image or choose from library</div></section>; }
function LivePreview() { return <section data-testid="live-preview-card" className="rounded-2xl border border-border bg-card p-4"><p className="font-bold">Live preview</p><div className="mt-3 rounded-xl bg-secondary p-4"><p className="text-xs font-bold text-primary">Study Plans</p><p className="font-serif text-2xl font-black">How to read the newspaper...</p><p className="mt-2 text-sm text-muted-foreground">Preview of student-facing article card.</p></div></section>; }
function ValidationCard() { return <section data-testid="validation-state-card" className="rounded-2xl border border-border bg-card p-4"><p className="font-bold">Validation</p><div className="mt-3 space-y-2 text-sm"><p><CheckCircle2 className="mr-2 inline h-4 w-4 text-primary" />Slug available</p><p><AlertTriangle className="mr-2 inline h-4 w-4 text-primary" />Meta description can be shorter</p><p><Copy className="mr-2 inline h-4 w-4 text-primary" />Related articles recommended</p></div></section>; }