/**
 * Generates supabase/seed.sql from the existing static hub content so the
 * database starts with the same blogs / faculties / branches / toppers the
 * site already shipped. Run with: bun run scripts/gen-seed.ts > supabase/seed.sql
 */
import { hubConfigs, type HubKind } from "../src/lib/hub-data";

const KINDS: HubKind[] = ["blog", "faculties", "branches", "toppers"];

const q = (value: string) => `'${value.replace(/'/g, "''")}'`;
const arr = (values: string[]) =>
  values.length ? `ARRAY[${values.map(q).join(", ")}]::text[]` : `'{}'::text[]`;
const json = (value: unknown) => `${q(JSON.stringify(value))}::jsonb`;

const lines: string[] = [
  "-- Auto-generated by scripts/gen-seed.ts. Do not edit by hand.",
  "-- Seeds initial published content for the public hub pages.",
  "truncate table public.content_items;",
  "",
];

for (const kind of KINDS) {
  hubConfigs[kind].items.forEach((item, index) => {
    lines.push(
      "insert into public.content_items " +
        "(kind, slug, title, subtitle, category, badges, facts, summary, sections, faqs, status, sort_order) values (",
      `  ${q(kind)}, ${q(item.slug)}, ${q(item.title)}, ${q(item.subtitle)}, ${q(item.category)},`,
      `  ${arr(item.badges)}, ${arr(item.facts)}, ${arr(item.summary)},`,
      `  ${json(item.sections)}, ${json(item.faqs)}, 'published', ${index}`,
      ");",
      "",
    );
  });
}

process.stdout.write(lines.join("\n"));
