/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToppersIndexRouteImport } from './routes/toppers/index'
import { Route as TestimonialsIndexRouteImport } from './routes/testimonials/index'
import { Route as FacultiesIndexRouteImport } from './routes/faculties/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as BranchesIndexRouteImport } from './routes/branches/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ToppersSlugRouteImport } from './routes/toppers/$slug'
import { Route as TestimonialsSlugRouteImport } from './routes/testimonials/$slug'
import { Route as FacultiesSlugRouteImport } from './routes/faculties/$slug'
import { Route as ExamsSlugRouteImport } from './routes/exams/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as ConversionSlugRouteImport } from './routes/conversion/$slug'
import { Route as BrandSlugRouteImport } from './routes/brand/$slug'
import { Route as BranchesSlugRouteImport } from './routes/branches/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminUsersModuleRouteImport } from './routes/admin/users/$module'
import { Route as AdminSettingsModuleRouteImport } from './routes/admin/settings/$module'
import { Route as AdminSeoModuleRouteImport } from './routes/admin/seo/$module'
import { Route as AdminResultsModuleRouteImport } from './routes/admin/results/$module'
import { Route as AdminOrganizationModuleRouteImport } from './routes/admin/organization/$module'
import { Route as AdminMarketingModuleRouteImport } from './routes/admin/marketing/$module'
import { Route as AdminCmsModuleRouteImport } from './routes/admin/cms/$module'
import { Route as AdminAcademicsModuleRouteImport } from './routes/admin/academics/$module'

const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToppersIndexRoute = ToppersIndexRouteImport.update({
  id: '/toppers/',
  path: '/toppers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsIndexRoute = TestimonialsIndexRouteImport.update({
  id: '/testimonials/',
  path: '/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesIndexRoute = FacultiesIndexRouteImport.update({
  id: '/faculties/',
  path: '/faculties/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToppersSlugRoute = ToppersSlugRouteImport.update({
  id: '/toppers/$slug',
  path: '/toppers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsSlugRoute = TestimonialsSlugRouteImport.update({
  id: '/testimonials/$slug',
  path: '/testimonials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesSlugRoute = FacultiesSlugRouteImport.update({
  id: '/faculties/$slug',
  path: '/faculties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsSlugRoute = ExamsSlugRouteImport.update({
  id: '/exams/$slug',
  path: '/exams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionSlugRoute = ConversionSlugRouteImport.update({
  id: '/conversion/$slug',
  path: '/conversion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesSlugRoute = BranchesSlugRouteImport.update({
  id: '/branches/$slug',
  path: '/branches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersModuleRoute = AdminUsersModuleRouteImport.update({
  id: '/admin/users/$module',
  path: '/admin/users/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsModuleRoute = AdminSettingsModuleRouteImport.update({
  id: '/admin/settings/$module',
  path: '/admin/settings/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoModuleRoute = AdminSeoModuleRouteImport.update({
  id: '/admin/seo/$module',
  path: '/admin/seo/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultsModuleRoute = AdminResultsModuleRouteImport.update({
  id: '/admin/results/$module',
  path: '/admin/results/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationModuleRoute = AdminOrganizationModuleRouteImport.update({
  id: '/admin/organization/$module',
  path: '/admin/organization/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingModuleRoute = AdminMarketingModuleRouteImport.update({
  id: '/admin/marketing/$module',
  path: '/admin/marketing/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsModuleRoute = AdminCmsModuleRouteImport.update({
  id: '/admin/cms/$module',
  path: '/admin/cms/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicsModuleRoute = AdminAcademicsModuleRouteImport.update({
  id: '/admin/academics/$module',
  path: '/admin/academics/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/conversion/$slug': typeof ConversionSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/faculties/$slug': typeof FacultiesSlugRoute
  '/testimonials/$slug': typeof TestimonialsSlugRoute
  '/toppers/$slug': typeof ToppersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/faculties/': typeof FacultiesIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/toppers/': typeof ToppersIndexRoute
  '/admin/academics/$module': typeof AdminAcademicsModuleRoute
  '/admin/cms/$module': typeof AdminCmsModuleRoute
  '/admin/marketing/$module': typeof AdminMarketingModuleRoute
  '/admin/organization/$module': typeof AdminOrganizationModuleRoute
  '/admin/results/$module': typeof AdminResultsModuleRoute
  '/admin/seo/$module': typeof AdminSeoModuleRoute
  '/admin/settings/$module': typeof AdminSettingsModuleRoute
  '/admin/users/$module': typeof AdminUsersModuleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/conversion/$slug': typeof ConversionSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/faculties/$slug': typeof FacultiesSlugRoute
  '/testimonials/$slug': typeof TestimonialsSlugRoute
  '/toppers/$slug': typeof ToppersSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/branches': typeof BranchesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/faculties': typeof FacultiesIndexRoute
  '/testimonials': typeof TestimonialsIndexRoute
  '/toppers': typeof ToppersIndexRoute
  '/admin/academics/$module': typeof AdminAcademicsModuleRoute
  '/admin/cms/$module': typeof AdminCmsModuleRoute
  '/admin/marketing/$module': typeof AdminMarketingModuleRoute
  '/admin/organization/$module': typeof AdminOrganizationModuleRoute
  '/admin/results/$module': typeof AdminResultsModuleRoute
  '/admin/seo/$module': typeof AdminSeoModuleRoute
  '/admin/settings/$module': typeof AdminSettingsModuleRoute
  '/admin/users/$module': typeof AdminUsersModuleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/scholarships': typeof ScholarshipsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/branches/$slug': typeof BranchesSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/conversion/$slug': typeof ConversionSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/exams/$slug': typeof ExamsSlugRoute
  '/faculties/$slug': typeof FacultiesSlugRoute
  '/testimonials/$slug': typeof TestimonialsSlugRoute
  '/toppers/$slug': typeof ToppersSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/faculties/': typeof FacultiesIndexRoute
  '/testimonials/': typeof TestimonialsIndexRoute
  '/toppers/': typeof ToppersIndexRoute
  '/admin/academics/$module': typeof AdminAcademicsModuleRoute
  '/admin/cms/$module': typeof AdminCmsModuleRoute
  '/admin/marketing/$module': typeof AdminMarketingModuleRoute
  '/admin/organization/$module': typeof AdminOrganizationModuleRoute
  '/admin/results/$module': typeof AdminResultsModuleRoute
  '/admin/seo/$module': typeof AdminSeoModuleRoute
  '/admin/settings/$module': typeof AdminSettingsModuleRoute
  '/admin/users/$module': typeof AdminUsersModuleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/faqs'
    | '/resources'
    | '/results'
    | '/scholarships'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/brand/$slug'
    | '/conversion/$slug'
    | '/courses/$slug'
    | '/exams/$slug'
    | '/faculties/$slug'
    | '/testimonials/$slug'
    | '/toppers/$slug'
    | '/admin/'
    | '/blog/'
    | '/branches/'
    | '/courses/'
    | '/faculties/'
    | '/testimonials/'
    | '/toppers/'
    | '/admin/academics/$module'
    | '/admin/cms/$module'
    | '/admin/marketing/$module'
    | '/admin/organization/$module'
    | '/admin/results/$module'
    | '/admin/seo/$module'
    | '/admin/settings/$module'
    | '/admin/users/$module'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/faqs'
    | '/resources'
    | '/results'
    | '/scholarships'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/brand/$slug'
    | '/conversion/$slug'
    | '/courses/$slug'
    | '/exams/$slug'
    | '/faculties/$slug'
    | '/testimonials/$slug'
    | '/toppers/$slug'
    | '/admin'
    | '/blog'
    | '/branches'
    | '/courses'
    | '/faculties'
    | '/testimonials'
    | '/toppers'
    | '/admin/academics/$module'
    | '/admin/cms/$module'
    | '/admin/marketing/$module'
    | '/admin/organization/$module'
    | '/admin/results/$module'
    | '/admin/seo/$module'
    | '/admin/settings/$module'
    | '/admin/users/$module'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/faqs'
    | '/resources'
    | '/results'
    | '/scholarships'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/blog/$slug'
    | '/branches/$slug'
    | '/brand/$slug'
    | '/conversion/$slug'
    | '/courses/$slug'
    | '/exams/$slug'
    | '/faculties/$slug'
    | '/testimonials/$slug'
    | '/toppers/$slug'
    | '/admin/'
    | '/blog/'
    | '/branches/'
    | '/courses/'
    | '/faculties/'
    | '/testimonials/'
    | '/toppers/'
    | '/admin/academics/$module'
    | '/admin/cms/$module'
    | '/admin/marketing/$module'
    | '/admin/organization/$module'
    | '/admin/results/$module'
    | '/admin/seo/$module'
    | '/admin/settings/$module'
    | '/admin/users/$module'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  FaqsRoute: typeof FaqsRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BranchesSlugRoute: typeof BranchesSlugRoute
  BrandSlugRoute: typeof BrandSlugRoute
  ConversionSlugRoute: typeof ConversionSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  ExamsSlugRoute: typeof ExamsSlugRoute
  FacultiesSlugRoute: typeof FacultiesSlugRoute
  TestimonialsSlugRoute: typeof TestimonialsSlugRoute
  ToppersSlugRoute: typeof ToppersSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  FacultiesIndexRoute: typeof FacultiesIndexRoute
  TestimonialsIndexRoute: typeof TestimonialsIndexRoute
  ToppersIndexRoute: typeof ToppersIndexRoute
  AdminAcademicsModuleRoute: typeof AdminAcademicsModuleRoute
  AdminCmsModuleRoute: typeof AdminCmsModuleRoute
  AdminMarketingModuleRoute: typeof AdminMarketingModuleRoute
  AdminOrganizationModuleRoute: typeof AdminOrganizationModuleRoute
  AdminResultsModuleRoute: typeof AdminResultsModuleRoute
  AdminSeoModuleRoute: typeof AdminSeoModuleRoute
  AdminSettingsModuleRoute: typeof AdminSettingsModuleRoute
  AdminUsersModuleRoute: typeof AdminUsersModuleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toppers/': {
      id: '/toppers/'
      path: '/toppers'
      fullPath: '/toppers/'
      preLoaderRoute: typeof ToppersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/': {
      id: '/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof TestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties/': {
      id: '/faculties/'
      path: '/faculties'
      fullPath: '/faculties/'
      preLoaderRoute: typeof FacultiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toppers/$slug': {
      id: '/toppers/$slug'
      path: '/toppers/$slug'
      fullPath: '/toppers/$slug'
      preLoaderRoute: typeof ToppersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/$slug': {
      id: '/testimonials/$slug'
      path: '/testimonials/$slug'
      fullPath: '/testimonials/$slug'
      preLoaderRoute: typeof TestimonialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties/$slug': {
      id: '/faculties/$slug'
      path: '/faculties/$slug'
      fullPath: '/faculties/$slug'
      preLoaderRoute: typeof FacultiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$slug': {
      id: '/exams/$slug'
      path: '/exams/$slug'
      fullPath: '/exams/$slug'
      preLoaderRoute: typeof ExamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion/$slug': {
      id: '/conversion/$slug'
      path: '/conversion/$slug'
      fullPath: '/conversion/$slug'
      preLoaderRoute: typeof ConversionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$slug': {
      id: '/branches/$slug'
      path: '/branches/$slug'
      fullPath: '/branches/$slug'
      preLoaderRoute: typeof BranchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$module': {
      id: '/admin/users/$module'
      path: '/admin/users/$module'
      fullPath: '/admin/users/$module'
      preLoaderRoute: typeof AdminUsersModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/$module': {
      id: '/admin/settings/$module'
      path: '/admin/settings/$module'
      fullPath: '/admin/settings/$module'
      preLoaderRoute: typeof AdminSettingsModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo/$module': {
      id: '/admin/seo/$module'
      path: '/admin/seo/$module'
      fullPath: '/admin/seo/$module'
      preLoaderRoute: typeof AdminSeoModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/results/$module': {
      id: '/admin/results/$module'
      path: '/admin/results/$module'
      fullPath: '/admin/results/$module'
      preLoaderRoute: typeof AdminResultsModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organization/$module': {
      id: '/admin/organization/$module'
      path: '/admin/organization/$module'
      fullPath: '/admin/organization/$module'
      preLoaderRoute: typeof AdminOrganizationModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing/$module': {
      id: '/admin/marketing/$module'
      path: '/admin/marketing/$module'
      fullPath: '/admin/marketing/$module'
      preLoaderRoute: typeof AdminMarketingModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/$module': {
      id: '/admin/cms/$module'
      path: '/admin/cms/$module'
      fullPath: '/admin/cms/$module'
      preLoaderRoute: typeof AdminCmsModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academics/$module': {
      id: '/admin/academics/$module'
      path: '/admin/academics/$module'
      fullPath: '/admin/academics/$module'
      preLoaderRoute: typeof AdminAcademicsModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  FaqsRoute: FaqsRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  BranchesSlugRoute: BranchesSlugRoute,
  BrandSlugRoute: BrandSlugRoute,
  ConversionSlugRoute: ConversionSlugRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  ExamsSlugRoute: ExamsSlugRoute,
  FacultiesSlugRoute: FacultiesSlugRoute,
  TestimonialsSlugRoute: TestimonialsSlugRoute,
  ToppersSlugRoute: ToppersSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  FacultiesIndexRoute: FacultiesIndexRoute,
  TestimonialsIndexRoute: TestimonialsIndexRoute,
  ToppersIndexRoute: ToppersIndexRoute,
  AdminAcademicsModuleRoute: AdminAcademicsModuleRoute,
  AdminCmsModuleRoute: AdminCmsModuleRoute,
  AdminMarketingModuleRoute: AdminMarketingModuleRoute,
  AdminOrganizationModuleRoute: AdminOrganizationModuleRoute,
  AdminResultsModuleRoute: AdminResultsModuleRoute,
  AdminSeoModuleRoute: AdminSeoModuleRoute,
  AdminSettingsModuleRoute: AdminSettingsModuleRoute,
  AdminUsersModuleRoute: AdminUsersModuleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
